version: "3"
services: 
  ansible-server-container: 
    build: . 
    #context: https://github.com/Anujsewani/Ansible-Linux-container.git
      # dockerfile: Dockerfile
      #args:
              # - GIT_BRANCH=main
    container_name: ansible-server-container
    ports: 
      - "2222:22"
      - "80:80"
    networks: 
      net: 
        ipv4_address: 172.168.100.2
  ansible-client-container:
    image: sewani/ansible_linux:latest
    container_name: ansible-node-container
    ports:
      - "2223:22"
      - "81:80"
    networks: 
      net: 
        ipv4_address: 172.168.100.3
        
networks: 
  net: 
   driver: bridge 
   ipam: 
     config: 
       - subnet: 172.168.100.1/24
  
